availableTasks:
- TASK_ENCODE
- TASK_DECODE
custom: false
documentationUrl: https://www.instill.tech/docs/component/operator/base64
icon: assets/base64.svg
iconUrl: ''
id: base64
public: true
spec: {}
title: Base64
type: COMPONENT_TYPE_OPERATOR
tombstone: false
uid: 3a836447-c211-4134-9cc5-ad45e1cc467e
version: 0.1.0
sourceUrl: https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/operator/base64/v0
description: Encode or decode a string in Base64 format.
releaseStage: RELEASE_STAGE_ALPHA
