availableTasks:
  - TASK_GET
  - TASK_POST
  - TASK_PATCH
  - TASK_PUT
  - TASK_DELETE
  - TASK_HEAD
  - TASK_OPTIONS
custom: false
documentationUrl: https://instill-ai.dev/docs/component/generic/http
icon: assets/http.svg
iconUrl: ''
id: http
public: true
title: HTTP
description: Make requests to external HTTP APIs.
tombstone: false
type: COMPONENT_TYPE_GENERIC
uid: 5ee55a5c-6e30-4c7a-80e8-90165a729e0a
vendor: ''
vendorAttributes: {}
version: 0.2.0
sourceUrl: https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/generic/http/v0
releaseStage: RELEASE_STAGE_ALPHA
