availableTasks:
  - TASK_TEXT_GENERATION_CHAT
custom: false
documentationUrl: https://docs.instill-ai.com/docs/anthropic
icon: assets/anthropic.svg
id: anthropic
public: true
title: Anthropic
description: Connect the AI models served on the Anthropic Platform.
type: COMPONENT_TYPE_AI
uid: 42bdb620-74ad-486a-82da-25e45431b42c
vendor: Anthropic
vendorAttributes: {}
version: 0.1.1
sourceUrl: https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/ai/anthropic/v0
releaseStage: RELEASE_STAGE_ALPHA
