availableTasks:
  - TASK_FIND_PROSPECTS
documentationUrl: https://docs.instill-ai.com/docs/leadiq
icon: assets/leadiq.svg
id: leadiq
public: true
title: LeadIQ
vendor: LeadIQ
description: Search for prospects and enrich your leads.
tombstone: false
type: COMPONENT_TYPE_APPLICATION
uid: 9fbda0b2-e8a6-497f-bd26-7e3f0c40ea44
version: 0.1.0
sourceUrl: https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/application/leadiq/v0
releaseStage: RELEASE_STAGE_ALPHA
