availableTasks:
- TASK_TEXT_GENERATION_CHAT
documentationUrl: https://www.instill.tech/docs/component/ai/groq
icon: assets/groq.svg
id: groq
public: true
title: Groq
description: Connect the AI models served on GroqCloud.
type: COMPONENT_TYPE_AI
uid: d5e64e5c-2dd2-4358-82dd-0e3a035c2157
vendor: Groq
vendorAttributes: {}
version: 0.1.0
sourceUrl: https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/ai/groq/v0
releaseStage: RELEASE_STAGE_ALPHA
