availableTasks:
- TASK_APPEND
- TASK_ASSIGN
- TASK_CONCAT
- TASK_DIFFERENCE
- TASK_INTERSECTION
- TASK_SPLIT
- TASK_SYMMETRIC_DIFFERENCE
- TASK_UNION
custom: false
documentationUrl: https://www.instill.tech/docs/component/generic/collection
icon: assets/collection.svg
iconUrl: ''
id: collection
public: true
spec: {}
title: Collection
type: COMPONENT_TYPE_GENERIC
uid: eb611e31-fbe6-43ad-8671-5b9a2e351638
version: 0.1.0
sourceUrl: https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/generic/collection/v0
description: Manipulate collection-type data.
releaseStage: RELEASE_STAGE_ALPHA
