availableTasks:
- TASK_TEXT_GENERATION_CHAT
- TASK_TEXT_EMBEDDINGS
documentationUrl: https://www.instill.tech/docs/component/ai/ollama
icon: assets/ollama.svg
id: ollama
public: true
title: Ollama
description: Connect the AI models served with the Ollama library.
type: COMPONENT_TYPE_AI
uid: 5f6dcfc4-efd0-45a1-aae9-c9b4beb68a32
vendor: Ollama
vendorAttributes: {}
version: 0.1.0
sourceUrl: https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/ai/ollama/v0
releaseStage: RELEASE_STAGE_ALPHA
