availableTasks:
  - TASK_GET_TICKET
  - TASK_CREATE_TICKET
  - TASK_REPLY_TO_TICKET
  - TASK_CREATE_TICKET_NOTE
  - TASK_GET_ALL_CONVERSATIONS
  - TASK_GET_CONTACT
  - TASK_CREATE_CONTACT
  - TASK_GET_COMPANY
  - TASK_CREATE_COMPANY
  - TASK_GET_ALL
  - TASK_GET_PRODUCT
  - TASK_GET_AGENT
  - TASK_GET_ROLE
  - TASK_GET_GROUP
  - TASK_GET_SKILL
documentationUrl: https://instill-ai.dev/docs/component/application/freshdesk
icon: assets/freshdesk.svg
id: freshdesk
public: true
title: Freshdesk
description: Use Freshdesk API to manage tickets, contacts and more.
tombstone: false
type: COMPONENT_TYPE_APPLICATION
uid: e89b5830-bc28-4886-9e04-e3db6e0efe9f
vendor: Freshdesk
vendorAttributes: {}
version: 0.1.0
sourceUrl: https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/application/freshdesk/v0
releaseStage: RELEASE_STAGE_ALPHA
