availableTasks:
- TASK_CREATE_CAMPAIGN
- TASK_SETUP_CAMPAIGN
- TASK_SAVE_SEQUENCES
- TASK_GET_SEQUENCES
- TASK_ADD_LEADS
- TASK_ADD_SENDER_EMAIL
- TASK_UPDATE_CAMPAIGN_STATUS
- TASK_GET_CAMPAIGN_METRIC
- TASK_LIST_LEADS_STATUS
documentationUrl: https://www.instill.tech/docs/component/application/smartlead
icon: assets/smartlead.svg
id: smartlead
public: true
title: Smartlead
vendor: Smartlead
description: Organize your leads and helps you close more deals.
tombstone: false
type: COMPONENT_TYPE_APPLICATION
uid: 4a736615-025b-4edf-a736-2a3905b00704
version: 0.1.0
sourceUrl: https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/application/smartlead/v0
releaseStage: RELEASE_STAGE_ALPHA
